PHPUnitテストの追加
vektor-inc/vk-breadcrumb pull request #4
Opened 2022-04-06 07:12 UTC by shimotmk

#3 3

2022-04-08 03:44 UTC, kurudrive requested changes

2022-04-08 03:44 UTC, kurudrive commented on .wp-env.json
> +  },
@shimotmk mappings は人によって環境が違うので .wp-env.override.json に個別に書いていただく方が良いかなーと思いました。

```suggestion
```

2022-04-08 03:44 UTC, kurudrive commented on src/VkBreadcrumb.php
> +				'name'  => date( 'Y' ),
@shimotmk おや？ここは 

* 表示対象が年別とは限らない（月別か日別もある）
* get_the_archive_title() の中のフックを使ったりする（している）ので、使えなくなるのは困る

という理由で、get_the_archive_title() じゃないと都合が悪いです ＞＜

```suggestion
				'name'  => get_the_archive_title(),
```

2022-04-08 03:44 UTC, kurudrive commented on README.md
> +[ Spacification Change ] Changed the method of getting the date archive title from get_the_archive_title to date( 'Y' ).
```suggestion
```

2022-04-08 04:44 UTC, kurudrive commented
@shimotmk get_the_archive_title() を変更するといろいろ都合悪いので原則残す方向で再調整お願いしたいです  (￣人￣)

2022-04-08 04:57 UTC, shimotmk commented
@kurudrive 
わかりました

2022-04-08 05:01 UTC, shimotmk commented on .wp-env.json
> +  },
テストの実行には必要だと思ったのですが、無くてもテストは出来たのでwp-env自体を削除しました

2022-04-08 08:42 UTC, shimotmk commented
@kurudrive 
get_the_archive_titleをUnitテスト内で使用するとループ内にないためかis_dateの条件に入らずArchivesが返ってきてしまうことがあります
get_the_archive_titleのフィルターフックをここでは使わずにこの対応はできるのものなのでしょうか？
 
get_the_archive_titleコアのソースコード
https://github.com/WordPress/wordpress-develop/blob/342cd8ca524846037453fe1cf707b8de72095208/src/wp-includes/general-template.php#L1694-L1782

2022-04-11 03:13 UTC, shimotmk commented
@kurudrive 
やはりwp-envのmappingはGithub Actions上でphpunitテストを実行する上で必要があると思います。
なぜならtests/bootstrap.phpの32行目で読み込んでいるWordPressのtest関数がUnitテストの実行には必要だからです。
 
より良い方法があればご指摘お願いします

2022-04-11 08:55 UTC, kurudrive approved these changes

2022-04-11 08:59 UTC, kurudrive approved these changes

2022-04-11 09:01 UTC, merged

2022-04-11 09:01 UTC, kurudrive commented
@shimotmk ありがとうございました！